# SPDX-FileCopyrightText: 2025 The Anon Kode Authors
# SPDX-License-Identifier: GPL-3.0-only

name: Build and Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test:
    name: Build, Test, and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Need full history for git-versioner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Docker image
        run: docker build -t usbip-auto-attach-builder .

      - name: Run Tests using Docker
        # Mount workspace, set working dir, run make test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            usbip-auto-attach-builder \
            make test

      - name: Compile executables using Docker
        # Mount workspace, set working dir, run make all
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            usbip-auto-attach-builder \
            make all

      - name: Upload amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: usbip-auto-attach-amd64
          path: ${{ github.workspace }}/build/x64/usbip-auto-attach # Correct executable name
          if-no-files-found: error

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: usbip-auto-attach-arm64
          path: ${{ github.workspace }}/build/arm64/usbip-auto-attach # Correct executable name
          if-no-files-found: error
