# SPDX-FileCopyrightText: 2025 The Anon Kode Authors
# SPDX-License-Identifier: GPL-3.0-only

name: Build Executables

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build static executables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Docker image
        run: docker build -t auto-attach-builder .

      # No need to create output directory, Makefile does it

      - name: Compile executables using Docker
        # Mount workspace to same path, set working dir, run make
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            auto-attach-builder \
            make all

      - name: Upload amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-attach-amd64
          path: ${{ github.workspace }}/build/x64/auto-attach # Updated path
          if-no-files-found: error

      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-attach-arm64
          path: ${{ github.workspace }}/build/arm64/auto-attach # Updated path
          if-no-files-found: error
