# SPDX-FileCopyrightText: 2025 The Anon Kode Authors
# SPDX-License-Identifier: GPL-3.0-only

name: Create Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build_and_release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Need full history for git-versioner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Docker image
        run: docker build -t usbip-auto-attach-builder .

      - name: Compile executables using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            usbip-auto-attach-builder \
            make all
          zip -j usbip-auto-attach-amd64.zip build/x64/usbip-auto-attach
          zip -j usbip-auto-attach-arm64.zip build/arm64/usbip-auto-attach

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tag_name will default to the git tag which is what we want
          # release_name will be generated from the tag
          generate_release_notes: true
          make_latest: true
          files: |
            usbip-auto-attach-amd64.zip
            usbip-auto-attach-arm64.zip
          # draft: false # default is false
          # prerelease: false # default is false
