# SPDX-FileCopyrightText: 2025 The Anon Kode Authors
# SPDX-License-Identifier: GPL-3.0-only

name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Docker image
        run: docker build -t auto-attach-builder .

      # No need to create output directory, Makefile does it

      - name: Compile executables using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            auto-attach-builder \
            make all

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |-
            Static MUSL builds of the auto-attach utility.
            - `auto-attach-amd64`: Linux x86_64
            - `auto-attach-arm64`: Linux ARM64
          draft: false
          prerelease: false

      - name: Upload amd64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/x64/auto-attach # Updated path
          asset_name: auto-attach-amd64
          asset_content_type: application/octet-stream
          if-no-files-found: error

      - name: Upload arm64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/arm64/auto-attach # Updated path
          asset_name: auto-attach-arm64
          asset_content_type: application/octet-stream
          if-no-files-found: error
